language: node_js
node_js:
  - stable
install:
  - yarn install
script:
  - yarn build
  - yarn test
  - yarn cover
after_script: "cat coverage/lcov.info | coveralls"
deploy:
  provider: npm
  email: "kim5257app@gmail.com"
  api_key: $NPM_TOKEN